### ISSUE TITLE
Merge yours service files and AUR's

### ISSUE THREAD

**Issue by savely-krasovsky** [spyophobia/shadowsocks-rust-spec#1]
I guess they have good service: https://aur.archlinux.org/cgit/aur.git/tree/shadowsocks-rust@.service?h=shadowsocks-rust
Enhances securiry:
```
DynamicUser=yes
NoNewPrivileges=yes
```
And allows low ports:
`AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN`

Also in my opinion you should also do `$i.json`, it's more convenient.

**Comment by spyophobia** [comment]
I used to use `DynamicUser` but for some reason (which I can no longer remember now) I switched to using systmed-sysusers. See 030de3e. They both drop privileges so this is fine. As of `NoNewPrivileges` and `AmbientCapabilities`, yes I can add those.

---

> Also in my opinion you should also do `$i.json`, it's more convenient.

I'd argue that convenience is very personal and subjective: what's convenient for some might not be very good for others. Such is the case here: the reason I have each profile in a directory (i.e. `%E/shadowsocks-rust/local/%i/ss.json5` instead of `%E/shadowsocks-rust/local/%i.json5`) is that I personally have rather complex profiles with several plugin config files (which I imagine is rather common for plugin users). So it makes sense to group them into a directory. Of course, I also understand that for users who only have a singular `ss.json5` for their profile, this seems like a needless layer of nesting. Again, this is subjective.

So I think a better metric than "convenience" is extensibility". And on this front having the organisational capacity of a profile directory is clearly better.
